version: '3.1'
networks:
    req_network:
        name: req_network
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16   
        external: true
services:
    req_postgres:
        image: postgres
        container_name: req_postgres
        networks:
            req_network:  
                ipv4_address: 172.28.0.2
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=2000
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
    req_nginx:
        image: nginx
        container_name: req_nginx
        volumes:
            - ./web_contents:/usr/share/nginx/html:ro
        ports:
            - "8090:80"
        networks:
            req_network:  
                ipv4_address: 172.28.0.3  
    req_redis:
        image: redis:alpine
        container_name: req_redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis_data:/data
        networks:
            req_network:  
                ipv4_address: 172.28.0.4
    req_cloudflared:
        image: cloudflare/cloudflared
        container_name: req_cloudflared
        network_mode: "host"
        restart: always
        environment:
            - TUNNEL_ORIGIN_CERT=/etc/cloudflared/cert.pem
            - TUNNEL_EDGE_IP_VERSION=auto 
        volumes:
            - ./cloudflared:/etc/cloudflared
        command: tunnel run ab8aba21-d72d-4ecc-a9eb-f760f9591315
